--- # webserver
server:
  port: 9080
  context-path: /
  session:
    timeout: 1800

--- # logging
logging:
  level:
    root: INFO
    com: 
      digitalchina: INFO
      
#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: @jdbc.url@
    username: @jdbc.username@
    password: @jdbc.password@
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

--- # mybatis
mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持
  mapper-locations: classpath:mapper/*.xml

upms:
  url: @upms.url@
  interceptor:
    patterns: /**/*.do,/
